#!/usr/bin/env python3
"""
Triad Deployment Metrics Analyzer v1.6

Analyzes deployment metrics from JSONL files generated by the Triad runbook.
Provides insights on deployment success rates, timing, and trends.

Usage:
    ./analyze_deployment_metrics.py deployment_metrics.jsonl --days 30
    ./analyze_deployment_metrics.py deployment_metrics.jsonl --output report.json
"""

import argparse
import json
import sys
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional


def parse_timestamp(ts: str) -> datetime:
    """Parse ISO format timestamp."""
    try:
        return datetime.fromisoformat(ts.replace('Z', '+00:00'))
    except ValueError:
        # Try alternative formats
        for fmt in ['%Y-%m-%dT%H:%M:%S', '%Y-%m-%d %H:%M:%S']:
            try:
                return datetime.strptime(ts, fmt)
            except ValueError:
                continue
    raise ValueError(f"Unable to parse timestamp: {ts}")


def load_metrics(filepath: str, days: Optional[int] = None) -> list[dict]:
    """Load metrics from JSONL file."""
    metrics = []
    cutoff = None

    if days:
        cutoff = datetime.now() - timedelta(days=days)

    path = Path(filepath)
    if not path.exists():
        print(f"Warning: Metrics file not found: {filepath}")
        return []

    with open(path, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                metric = json.loads(line)
                if cutoff and 'timestamp' in metric:
                    ts = parse_timestamp(metric['timestamp'])
                    if ts.replace(tzinfo=None) < cutoff:
                        continue
                metrics.append(metric)
            except json.JSONDecodeError as e:
                print(f"Warning: Invalid JSON on line {line_num}: {e}")

    return metrics


def analyze_metrics(metrics: list[dict]) -> dict:
    """Analyze deployment metrics and return summary."""
    if not metrics:
        return {
            'total_events': 0,
            'message': 'No metrics data available'
        }

    analysis = {
        'total_events': len(metrics),
        'events_by_type': defaultdict(int),
        'events_by_status': defaultdict(int),
        'timeline': [],
        'success_rate': 0.0,
        'event_details': defaultdict(lambda: {'success': 0, 'failed': 0}),
    }

    # Count events by type and status
    for metric in metrics:
        event_type = metric.get('event', 'unknown')
        status = metric.get('status', 'unknown')

        analysis['events_by_type'][event_type] += 1
        analysis['events_by_status'][status] += 1

        if status == 'success':
            analysis['event_details'][event_type]['success'] += 1
        elif status == 'failed':
            analysis['event_details'][event_type]['failed'] += 1

        # Add to timeline
        if 'timestamp' in metric:
            analysis['timeline'].append({
                'timestamp': metric['timestamp'],
                'event': event_type,
                'status': status,
                'details': metric.get('details', '')
            })

    # Calculate success rate
    total_with_status = analysis['events_by_status'].get('success', 0) + \
                        analysis['events_by_status'].get('failed', 0)
    if total_with_status > 0:
        analysis['success_rate'] = (
            analysis['events_by_status'].get('success', 0) / total_with_status * 100
        )

    # Convert defaultdicts to regular dicts for JSON serialization
    analysis['events_by_type'] = dict(analysis['events_by_type'])
    analysis['events_by_status'] = dict(analysis['events_by_status'])
    analysis['event_details'] = {k: dict(v) for k, v in analysis['event_details'].items()}

    # Sort timeline by timestamp
    analysis['timeline'].sort(key=lambda x: x.get('timestamp', ''))

    return analysis


def print_report(analysis: dict) -> None:
    """Print formatted analysis report."""
    print("\n" + "=" * 60)
    print("  TRIAD DEPLOYMENT METRICS REPORT")
    print("=" * 60 + "\n")

    if analysis['total_events'] == 0:
        print("No metrics data available.")
        print("Run the triad_runbook to generate deployment metrics.\n")
        return

    # Overview
    print(f"Total Events: {analysis['total_events']}")
    print(f"Success Rate: {analysis['success_rate']:.1f}%\n")

    # Events by Status
    print("-" * 40)
    print("Events by Status:")
    print("-" * 40)
    for status, count in sorted(analysis['events_by_status'].items()):
        indicator = "[OK]" if status == "success" else "[!!]" if status == "failed" else "[--]"
        print(f"  {indicator} {status}: {count}")
    print()

    # Events by Type
    print("-" * 40)
    print("Events by Type:")
    print("-" * 40)
    for event_type, count in sorted(analysis['events_by_type'].items()):
        details = analysis['event_details'].get(event_type, {})
        success = details.get('success', 0)
        failed = details.get('failed', 0)
        rate = (success / (success + failed) * 100) if (success + failed) > 0 else 0
        print(f"  {event_type}: {count} ({rate:.0f}% success)")
    print()

    # Recent Timeline (last 10 events)
    if analysis['timeline']:
        print("-" * 40)
        print("Recent Events (last 10):")
        print("-" * 40)
        for event in analysis['timeline'][-10:]:
            ts = event.get('timestamp', 'N/A')[:19]
            status_icon = "+" if event['status'] == 'success' else "-"
            print(f"  [{status_icon}] {ts} | {event['event']}")
            if event.get('details'):
                print(f"      Details: {event['details']}")

    print("\n" + "=" * 60 + "\n")


def generate_json_report(analysis: dict, output_path: str) -> None:
    """Generate JSON report file."""
    report = {
        'generated_at': datetime.now().isoformat(),
        'summary': {
            'total_events': analysis['total_events'],
            'success_rate': analysis['success_rate'],
        },
        'events_by_type': analysis['events_by_type'],
        'events_by_status': analysis['events_by_status'],
        'event_details': analysis['event_details'],
        'timeline': analysis['timeline']
    }

    with open(output_path, 'w') as f:
        json.dump(report, f, indent=2)

    print(f"JSON report saved to: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Analyze Triad deployment metrics from JSONL files.'
    )
    parser.add_argument(
        'metrics_file',
        help='Path to the deployment_metrics.jsonl file'
    )
    parser.add_argument(
        '--days',
        type=int,
        default=None,
        help='Only analyze metrics from the last N days'
    )
    parser.add_argument(
        '--output',
        type=str,
        default=None,
        help='Output JSON report to specified file'
    )
    parser.add_argument(
        '--quiet',
        action='store_true',
        help='Suppress console output (use with --output)'
    )

    args = parser.parse_args()

    # Load metrics
    metrics = load_metrics(args.metrics_file, args.days)

    # Analyze
    analysis = analyze_metrics(metrics)

    # Output
    if not args.quiet:
        print_report(analysis)

    if args.output:
        generate_json_report(analysis, args.output)

    # Exit with error if there were failures
    if analysis.get('events_by_status', {}).get('failed', 0) > 0:
        sys.exit(1)

    sys.exit(0)


if __name__ == '__main__':
    main()
